#!/bin/sh
git diff --cached --quiet -- scripts && exit 0
git diff --name-only -- scripts | grep --fixed-strings "$(git diff --cached --name-only -- scripts)" && exit 1
version="$(date --utc +%Y.%m.%d.%H%M%S)"
git diff --cached --name-only -- scripts | while read -r file; do
	sed --in-place "s/@version .*/@version $version/" "$file"
	git add "$file"
done
