#!/bin/sh
git diff --quiet --cached -- scripts && exit 0
git diff --name-only -- scripts | grep -F "$(git diff --cached --name-only -- scripts)" && exit 1
version="$(date -u +%Y.%m.%d.%H%M%S)"
git diff --cached --name-only -- scripts | while read -r file; do
	sed -i "s/@version .*/@version $version/" "$file"
	git add "$file"
done
